import type { Metadata } from "next";
import { Bebas_Neue, Outfit, JetBrains_Mono } from "next/font/google"

const display = Bebas_Neue({ subsets: ["latin"], weight: "400", variable: "--font-display" })
const body = Outfit({ subsets: ["latin"], variable: "--font-body" })
const mono = JetBrains_Mono({ subsets: ["latin"], variable: "--font-mono" })

import Navbar from "@/components/layout/Navbar";
import DetailModal from "@/components/modals/DetailModal";
import PlayerOverlay from "@/components/player/PlayerOverlay";
import Toast from "@/components/ui/Toast";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${display.variable} ${body.variable} ${mono.variable} antialiased`}
      >
        <Navbar />
        <main className="min-h-screen bg-[var(--color-bg)]">
          {children}
        </main>
        <DetailModal />
        <PlayerOverlay />
        <Toast />
      </body>
    </html>
  );
}
